import ContextWorkspaceCore

public typealias WorkspacePersonaDraft = ContextWorkspaceCore.WorkspacePersonaDraft
public typealias WorkspacePersonaDraftValidation = ContextWorkspaceCore.WorkspacePersonaDraftValidation
