import ContextWorkspaceCore

public typealias WorkspaceEssentialManaging = ContextWorkspaceCore.WorkspaceEssentialManaging
public typealias WorkspaceEssentialManager = ContextWorkspaceCore.WorkspaceEssentialManager
public typealias WorkspaceEssentialManagerDependencies = ContextWorkspaceCore.WorkspaceEssentialManagerDependencies
