import ContextWorkspaceCore

public typealias WorkspaceSessionDraft = ContextWorkspaceCore.WorkspaceSessionDraft
public typealias WorkspaceSessionManagerError = ContextWorkspaceCore.WorkspaceSessionManagerError
public typealias WorkspaceSessionManaging = ContextWorkspaceCore.WorkspaceSessionManaging
public typealias WorkspaceSessionManager = ContextWorkspaceCore.WorkspaceSessionManager
public typealias WorkspaceSessionManagerDependencies = ContextWorkspaceCore.WorkspaceSessionManagerDependencies
