import ContextWorkspaceCore

public typealias WorkspaceLibraryEntityManaging = ContextWorkspaceCore.WorkspaceLibraryEntityManaging
public typealias WorkspaceLibraryEntityManager = ContextWorkspaceCore.WorkspaceLibraryEntityManager
public typealias WorkspaceLibraryEntityManagerDependencies = ContextWorkspaceCore
  .WorkspaceLibraryEntityManagerDependencies
